#!/bin/bash

# This query is only for versions of postgres >=9.2 that
# have pg_stat_activity.state as a separate field.

if [ -n "$1" ] ; then
    db="-d $1"
elif [ -n "${HPPTDATABASE}" ] ; then
    db="-d ${HPPTDATABASE}"
fi

psql $db ${HPPTOPTS} -c "
SELECT
  state,count(*)
FROM pg_stat_activity
WHERE
  pid != pg_backend_pid()
GROUP BY state
"

# TODO Some users might prefer filtering only connections to a set of databases, such as:
#
#   AND datname = 'dbXX'
#
# This would best be done as an additional command line option to this program, since
# it's not necessarily the same as the database to connect to, especially when connecting
# as a database superuser for monitoring.
