#!/bin/bash

# TODO Update for 9.2 pg_stat_activity change

if [ -n "${HPPTDATABASE}" ] ; then
    db="-d ${HPPTDATABASE}"
fi

psql $db ${HPPTOPTS} -c "
select 'IDLE' as state, procpid,now() - query_start as runtime,current_query from pg_stat_activity where query_start < (now() - '3 hours'::interval) and current_query='<IDLE>' order by query_start limit 40
"

# List of dead session process IDs, suitable for sending into kill
psql -d $db -At -q -c "
select procpid from pg_stat_activity where query_start < (now() - '3 hours'::interval) and current_query='<IDLE>' order by query_start
" | xargs echo


