#!/bin/bash

# TODO Update for 9.2 pg_stat_activity change

if [ -n "${HPPTDATABASE}" ] ; then
    db="-d ${HPPTDATABASE}"
fi

psql $db ${HPPTOPTS} -c "
SELECT
  state,
  pid,
  now() - query_start AS runtime,
  query
FROM pg_stat_activity
WHERE
  query_start < (now() - '3 hours'::interval) AND
  (state='idle' OR state='idle in transaction')
order by query_start limit 40
"

# List of dead session process IDs, suitable for sending into kill
psql $db -At -q -c "
SELECT
  pid
FROM pg_stat_activity
WHERE
  query_start < (now() - '3 hours'::interval) AND 
  (state='idle' OR state='idle in transaction')
ORDER BY query_start
" | xargs echo

