#!/bin/bash

# Copyright 2013-2015 Gregory Smith gsmith@westnet.com

# TODO Update for PostgreSQL 9.2 pg_stat_activity

if [ -n "${HPPTDATABASE}" ] ; then
    db="-d ${HPPTDATABASE}"
fi

psql $db ${HPPTOPTS} -c "
select '!IDLE' as state, procpid,now() - query_start as runtime,current_query from pg_stat_activity where current_query!='<IDLE>' order by query_start limit 20
"

psql $db ${HPPTOPTS} -c "
select 'IDLE' as state, procpid,now() - query_start as runtime,current_query from pg_stat_activity where current_query='<IDLE>' order by query_start limit 40
"

