#!/bin/bash

# Copyright 2013-2015 Gregory Smith gsmith@westnet.com

# TODO Update for PostgreSQL 9.2 pg_stat_activity

if [ -n "${HPPTDATABASE}" ] ; then
    db="-d ${HPPTDATABASE}"
fi

psql $db ${HPPTOPTS} -c "
SELECT
  state,
  pid,
  now() - query_start as runtime,
  query
FROM pg_stat_activity
WHERE
  NOT (state='idle' OR state='idle in transaction')
ORDER BY query_start
LIMIT 20
"

psql $db ${HPPTOPTS} -c "
SELECT
  state,
  pid,
  now() - query_start AS runtime,
  query
FROM pg_stat_activity
WHERE
  (state='idle' OR state='idle in transaction')
ORDER BY query_start
LIMIT 40
"

